/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddAccountDialog: typeof import('./src/components/gacha/AddAccountDialog.vue')['default']
    BannerCard: typeof import('./src/components/gacha/BannerCard.vue')['default']
    DonutChart: typeof import('./src/components/charts/DonutChart.vue')['default']
    MetadataUpdateDialog: typeof import('./src/components/MetadataUpdateDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitButtonSelect: typeof import('./src/components/SplitButtonSelect.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UpdateDialog: typeof import('./src/components/UpdateDialog.vue')['default']
    VarAvatar: typeof import('@varlet/ui')['_AvatarComponent']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarButtonGroup: typeof import('@varlet/ui')['_ButtonGroupComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCell: typeof import('@varlet/ui')['_CellComponent']
    VarCheckbox: typeof import('@varlet/ui')['_CheckboxComponent']
    VarChip: typeof import('@varlet/ui')['_ChipComponent']
    VarCollapse: typeof import('@varlet/ui')['_CollapseComponent']
    VarCollapseItem: typeof import('@varlet/ui')['_CollapseItemComponent']
    VarDialog: typeof import('@varlet/ui')['_DialogComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarLoading: typeof import('@varlet/ui')['_LoadingComponent']
    VarMenu: typeof import('@varlet/ui')['_MenuComponent']
    VarOverlay: typeof import('@varlet/ui')['_OverlayComponent']
    VarPaper: typeof import('@varlet/ui')['_PaperComponent']
    VarProgress: typeof import('@varlet/ui')['_ProgressComponent']
    VarResult: typeof import('@varlet/ui')['_ResultComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarStep: typeof import('@varlet/ui')['_StepComponent']
    VarSteps: typeof import('@varlet/ui')['_StepsComponent']
    VarSwitch: typeof import('@varlet/ui')['_SwitchComponent']
  }
  export interface GlobalDirectives {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
