export const nekoTheme = {
  "light": {
    "--hsl-primary": "337, 41%, 42%",
    "--color-primary": "hsla(var(--hsl-primary), 1)",
    "--hsl-on-primary": "0, 0%, 100%",
    "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
    "--hsl-primary-container": "344, 100%, 93%",
    "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
    "--hsl-on-primary-container": "331, 100%, 12%",
    "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
    "--hsl-info": "342, 15%, 40%",
    "--color-info": "hsla(var(--hsl-info), 1)",
    "--hsl-on-info": "0, 0%, 100%",
    "--color-on-info": "hsla(var(--hsl-on-info), 1)",
    "--hsl-info-container": "344, 100%, 93%",
    "--color-info-container": "hsla(var(--hsl-info-container), 1)",
    "--hsl-on-info-container": "341, 34%, 13%",
    "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
    "--hsl-warning": "28, 40%, 35%",
    "--color-warning": "hsla(var(--hsl-warning), 1)",
    "--hsl-on-warning": "0, 0%, 100%",
    "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
    "--hsl-warning-container": "26, 100%, 88%",
    "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
    "--hsl-on-warning-container": "27, 100%, 9%",
    "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
    "--hsl-danger": "0, 75%, 42%",
    "--color-danger": "hsla(var(--hsl-danger), 1)",
    "--hsl-on-danger": "0, 0%, 100%",
    "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
    "--hsl-danger-container": "6, 100%, 92%",
    "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
    "--hsl-on-danger-container": "358, 100%, 13%",
    "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
    "--hsl-body": "300, 100%, 99%",
    "--color-body": "hsla(var(--hsl-body), 1)",
    "--hsl-text": "350, 10%, 11%",
    "--color-text": "hsla(var(--hsl-text), 1)",
    "--hsl-on-surface-variant": "343, 9%, 29%",
    "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
    "--hsl-outline": "345, 7%, 48%",
    "--color-outline": "hsla(var(--hsl-outline), 1)",
    "--hsl-inverse-surface": "350, 6%, 20%",
    "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)",
    "--select-label-font-size": "14px",

    "--option-font-size": "14px",
    "--color-logo-text": "#242424",
    "--color-logo-accent": "#d6d60b",
    "--color-content-background": "rgba(255, 255, 255, 0.85)",
    "--color-content-border": "rgba(0, 0, 0, 0.08)",
    "--color-toolbar-bg": "rgba(255, 255, 255, 0.92)",
    "--color-card-bg": "rgba(255, 255, 255, 0.82)",
    "--color-border-subtle": "rgba(0, 0, 0, 0.06)",
    "--color-record-item-bg": "rgba(212, 212, 212, 0.2)",
    "--color-scrollbar-thumb": "rgba(0, 0, 0, 0.28)",
    "--color-scrollbar-thumb-hover": "rgba(0, 0, 0, 0.38)",
    "--collapse-content-padding": "0"
  },
  "dark": {
    "--hsl-primary": "341, 100%, 85%",
    "--color-primary": "hsla(var(--hsl-primary), 1)",
    "--hsl-on-primary": "333, 69%, 22%",
    "--color-on-primary": "hsla(var(--hsl-on-primary), 1)",
    "--hsl-primary-container": "336, 50%, 32%",
    "--color-primary-container": "hsla(var(--hsl-primary-container), 1)",
    "--hsl-on-primary-container": "344, 100%, 93%",
    "--color-on-primary-container": "hsla(var(--hsl-on-primary-container), 1)",
    "--hsl-info": "344, 39%, 81%",
    "--color-info": "hsla(var(--hsl-info), 1)",
    "--hsl-on-info": "341, 23%, 21%",
    "--color-on-info": "hsla(var(--hsl-on-info), 1)",
    "--hsl-info-container": "342, 18%, 30%",
    "--color-info-container": "hsla(var(--hsl-info-container), 1)",
    "--hsl-on-info-container": "344, 100%, 93%",
    "--color-on-info-container": "hsla(var(--hsl-on-info-container), 1)",
    "--hsl-warning": "26, 74%, 76%",
    "--color-warning": "hsla(var(--hsl-warning), 1)",
    "--hsl-on-warning": "29, 71%, 16%",
    "--color-on-warning": "hsla(var(--hsl-on-warning), 1)",
    "--hsl-warning-container": "28, 51%, 25%",
    "--color-warning-container": "hsla(var(--hsl-warning-container), 1)",
    "--hsl-on-warning-container": "26, 100%, 88%",
    "--color-on-warning-container": "hsla(var(--hsl-on-warning-container), 1)",
    "--hsl-danger": "6, 100%, 84%",
    "--color-danger": "hsla(var(--hsl-danger), 1)",
    "--hsl-on-danger": "357, 100%, 21%",
    "--color-on-danger": "hsla(var(--hsl-on-danger), 1)",
    "--hsl-danger-container": "356, 100%, 29%",
    "--color-danger-container": "hsla(var(--hsl-danger-container), 1)",
    "--hsl-on-danger-container": "6, 100%, 84%",
    "--color-on-danger-container": "hsla(var(--hsl-on-danger-container), 1)",
    "--hsl-body": "350, 10%, 11%",
    "--color-body": "hsla(var(--hsl-body), 1)",
    "--hsl-text": "355, 22%, 90%",
    "--color-text": "hsla(var(--hsl-text), 1)",
    "--hsl-on-surface-variant": "347, 18%, 80%",
    "--color-on-surface-variant": "hsla(var(--hsl-on-surface-variant), 1)",
    "--hsl-outline": "347, 8%, 58%",
    "--color-outline": "hsla(var(--hsl-outline), 1)",
    "--hsl-inverse-surface": "355, 22%, 90%",
    "--color-inverse-surface": "hsla(var(--hsl-inverse-surface), 1)",
    "--select-label-font-size": "14px",
    "--option-font-size": "14px",
    "--color-logo-text": "#ffffff",
    "--color-logo-accent": "#FFFF21",
    "--color-content-background": "rgba(0, 0, 0, 0.22)",
    "--color-content-border": "rgba(255, 255, 255, 0.08)",
    "--color-toolbar-bg": "rgba(0, 0, 0, 0.28)",
    "--color-card-bg": "rgba(0, 0, 0, 0.22)",
    "--color-border-subtle": "rgba(255, 255, 255, 0.08)",
    "--color-record-item-bg": "rgba(255, 255, 255, 0.06)",
    "--color-scrollbar-thumb": "rgba(255, 255, 255, 0.28)",
    "--color-scrollbar-thumb-hover": "rgba(255, 255, 255, 0.38)",
    "--collapse-content-padding": "0"
  }
}